{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.ricoh.cotos",
    "module": "electric-common-libraries",
    "version": "0.0.306",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "electric-common-libraries-0.0.306-plain.jar",
          "url": "electric-common-libraries-0.0.306-plain.jar",
          "size": 829933,
          "sha512": "6571467361f51160ddb14e345d89f69b0c9b2ed2b58afc207ab5b80954ce6e89ac14fb0f6b9c211152358aee2184b0b269f88959cb9eeb767103798b2760f6d7",
          "sha256": "4deae0e1f5839e1e4c6e2128be69ced57a2fd9ec5f2512c10804cb604e377fcd",
          "sha1": "55b74df06085c104d334397c8fa6b8b9b2b10682",
          "md5": "292a971399416b7c07f197894be8cdd4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-mail",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.14"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.2.Final"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.2.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jxls",
          "module": "jxls",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jxls",
          "module": "jxls-poi",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "3.17"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "jp.co.ricoh.cotos",
          "module": "dentos-common-libraries",
          "version": {
            "requires": "0.0.363"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger2",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger-ui",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "io.swagger",
          "module": "swagger-core",
          "version": {
            "requires": "1.5.15"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.apache.axis",
          "module": "axis",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "javax.xml",
          "module": "jaxrpc-api",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "wsdl4j",
          "module": "wsdl4j",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "commons-discovery",
          "module": "commons-discovery",
          "version": {
            "requires": "0.5"
          }
        },
        {
          "group": "log4j",
          "module": "log4j",
          "version": {
            "requires": "1.2.17"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.17.5"
          }
        },
        {
          "group": "com.oracle.database.jdbc",
          "module": "ojdbc8",
          "version": {
            "requires": "23.7.0.25.01"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-devtools",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "electric-common-libraries-0.0.306-plain.jar",
          "url": "electric-common-libraries-0.0.306-plain.jar",
          "size": 829933,
          "sha512": "6571467361f51160ddb14e345d89f69b0c9b2ed2b58afc207ab5b80954ce6e89ac14fb0f6b9c211152358aee2184b0b269f88959cb9eeb767103798b2760f6d7",
          "sha256": "4deae0e1f5839e1e4c6e2128be69ced57a2fd9ec5f2512c10804cb604e377fcd",
          "sha1": "55b74df06085c104d334397c8fa6b8b9b2b10682",
          "md5": "292a971399416b7c07f197894be8cdd4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "electric-common-libraries-0.0.306-sources.jar",
          "url": "electric-common-libraries-0.0.306-sources.jar",
          "size": 282028,
          "sha512": "2cf92dfabf0da843f5e642930526eee65dbe8cc95018f22efcc2a16dfdfa984368779ee52c600f62b990587ad7b3ecc9a57c384c0b91486ffc4a880fc0f3b379",
          "sha256": "15edb2a29bcf3891596488dc58f0ae3984bc03e41e20d8d1d915bc8086b500b9",
          "sha1": "9c947fa9fd84cdc22d3bac0ca19563ae02f07b89",
          "md5": "c1fa61390d5a3d079121891a670b4e6f"
        }
      ]
    }
  ]
}
