{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.ricoh.cotos",
    "module": "electric-common-libraries",
    "version": "0.0.307",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "electric-common-libraries-0.0.307-plain.jar",
          "url": "electric-common-libraries-0.0.307-plain.jar",
          "size": 829933,
          "sha512": "c40f9814e246df1a5ecefb4de55830d06476f66024ef04ea2c93226abff5150dcca246bdb3b76c891018650246625eb275b3745eb650cc704bb60ad72af93737",
          "sha256": "830d43a83264e77b54c2ed0b0d41f6b7533bb8acc0775be2bc7f88df42a0f510",
          "sha1": "4ccb9bed1f70912a4ff5203f308b396f8315656a",
          "md5": "b1dc074fc5838e57943a8810fe0a7351"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-mail",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.14"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.2.Final"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.2.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jxls",
          "module": "jxls",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jxls",
          "module": "jxls-poi",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "3.17"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "jp.co.ricoh.cotos",
          "module": "dentos-common-libraries",
          "version": {
            "requires": "0.0.363"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger2",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger-ui",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "io.swagger",
          "module": "swagger-core",
          "version": {
            "requires": "1.5.15"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.apache.axis",
          "module": "axis",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "javax.xml",
          "module": "jaxrpc-api",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "wsdl4j",
          "module": "wsdl4j",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "commons-discovery",
          "module": "commons-discovery",
          "version": {
            "requires": "0.5"
          }
        },
        {
          "group": "log4j",
          "module": "log4j",
          "version": {
            "requires": "1.2.17"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.17.5"
          }
        },
        {
          "group": "com.oracle.database.jdbc",
          "module": "ojdbc8",
          "version": {
            "requires": "23.7.0.25.01"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-devtools",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "electric-common-libraries-0.0.307-plain.jar",
          "url": "electric-common-libraries-0.0.307-plain.jar",
          "size": 829933,
          "sha512": "c40f9814e246df1a5ecefb4de55830d06476f66024ef04ea2c93226abff5150dcca246bdb3b76c891018650246625eb275b3745eb650cc704bb60ad72af93737",
          "sha256": "830d43a83264e77b54c2ed0b0d41f6b7533bb8acc0775be2bc7f88df42a0f510",
          "sha1": "4ccb9bed1f70912a4ff5203f308b396f8315656a",
          "md5": "b1dc074fc5838e57943a8810fe0a7351"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "electric-common-libraries-0.0.307-sources.jar",
          "url": "electric-common-libraries-0.0.307-sources.jar",
          "size": 282028,
          "sha512": "c82bb0336e71dac305a7b92bec45af25845c5137b2e8bfe8dc5c8013bda2e95eddc1ad3d4a7ac5f37aff504c9c8d2a1b3836283dcbbe45ae8243ae1328f7d3cb",
          "sha256": "c0a73d567ed4bb3dea18929e3983f89b75bae385cc957458759afe0aca002cc8",
          "sha1": "52dc16f4c70c648d0aad9a80e71c2d31035297f2",
          "md5": "79e1c44c89b77bf5f71b73060703afd2"
        }
      ]
    }
  ]
}
