{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.ricoh.cotos",
    "module": "dentos-isliving",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dentos-isliving-0.0.6-plain.jar",
          "url": "dentos-isliving-0.0.6-plain.jar",
          "size": 2688,
          "sha512": "25705d3d130339d62a09d266c183621861cf7abdc8f53c945950d815560a1d9c60a4ceef84d4be28da1c86abf2ece1b16ccf390c4ff73f11948d9aec00e0e577",
          "sha256": "6bb6f3086e57d75550e313976cfec899794a37cdf9f1e0df3c334c3d3ddd285d",
          "sha1": "6f1398ac303b42273c2c4bf78ed375706c4fa9ea",
          "md5": "1b4feea862009091768a83670111be9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "jp.co.ricoh.cotos",
          "module": "dentos-common-libraries",
          "version": {
            "requires": "0.0.370"
          }
        }
      ],
      "files": [
        {
          "name": "dentos-isliving-0.0.6-plain.jar",
          "url": "dentos-isliving-0.0.6-plain.jar",
          "size": 2688,
          "sha512": "25705d3d130339d62a09d266c183621861cf7abdc8f53c945950d815560a1d9c60a4ceef84d4be28da1c86abf2ece1b16ccf390c4ff73f11948d9aec00e0e577",
          "sha256": "6bb6f3086e57d75550e313976cfec899794a37cdf9f1e0df3c334c3d3ddd285d",
          "sha1": "6f1398ac303b42273c2c4bf78ed375706c4fa9ea",
          "md5": "1b4feea862009091768a83670111be9b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dentos-isliving-0.0.6-sources.jar",
          "url": "dentos-isliving-0.0.6-sources.jar",
          "size": 2101,
          "sha512": "53b2a6780c631629383ea59212c6bd4686f341efa64007c67cf7929a9b4285d12c7744ec5d38f7bb2d1a93e24b07ed0dafd2eec8b896abb9bcdcfdd28b9b35fd",
          "sha256": "aa9b82b2af7a44daabbbceb04a70fb03f2de5794ef81311604c77ab1c2745512",
          "sha1": "9ca86602215480f74b24f4df94f3cf29c6bdea31",
          "md5": "665abd65336a942f2bde453ff09a7fc4"
        }
      ]
    }
  ]
}
