{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.ricoh.cotos",
    "module": "electric-common-libraries",
    "version": "0.0.308",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "electric-common-libraries-0.0.308-plain.jar",
          "url": "electric-common-libraries-0.0.308-plain.jar",
          "size": 828653,
          "sha512": "9008ef1f4a6ce61d8a95258c6928822c43f824462584e3d11e7d7043762a5afb9b51b9621e974565ac4df7cd770e2cfacdbf3cd2015e606194fccdd931cdc566",
          "sha256": "c362b30551837e3114dd966d45de627191eb46804860ccd90e42b908ed32ee9a",
          "sha1": "e198ff7c2d232ce68e8b085ad6498559e6eb3197",
          "md5": "52c94da683c2bef728584f461a80479a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-mail",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.14"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.2.Final"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.2.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jxls",
          "module": "jxls",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jxls",
          "module": "jxls-poi",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "3.17"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "jp.co.ricoh.cotos",
          "module": "dentos-common-libraries",
          "version": {
            "requires": "0.0.363"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger2",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger-ui",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "io.swagger",
          "module": "swagger-core",
          "version": {
            "requires": "1.5.15"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.apache.axis",
          "module": "axis",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "javax.xml",
          "module": "jaxrpc-api",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "wsdl4j",
          "module": "wsdl4j",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "commons-discovery",
          "module": "commons-discovery",
          "version": {
            "requires": "0.5"
          }
        },
        {
          "group": "log4j",
          "module": "log4j",
          "version": {
            "requires": "1.2.17"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.17.5"
          }
        },
        {
          "group": "com.oracle.database.jdbc",
          "module": "ojdbc8",
          "version": {
            "requires": "23.7.0.25.01"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-devtools",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "electric-common-libraries-0.0.308-plain.jar",
          "url": "electric-common-libraries-0.0.308-plain.jar",
          "size": 828653,
          "sha512": "9008ef1f4a6ce61d8a95258c6928822c43f824462584e3d11e7d7043762a5afb9b51b9621e974565ac4df7cd770e2cfacdbf3cd2015e606194fccdd931cdc566",
          "sha256": "c362b30551837e3114dd966d45de627191eb46804860ccd90e42b908ed32ee9a",
          "sha1": "e198ff7c2d232ce68e8b085ad6498559e6eb3197",
          "md5": "52c94da683c2bef728584f461a80479a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "electric-common-libraries-0.0.308-sources.jar",
          "url": "electric-common-libraries-0.0.308-sources.jar",
          "size": 282132,
          "sha512": "cf4925b9183cef77564daca5a5d68d55c4c71eacd3e78a2a3900eca3ddcb9220a3263ca32df8d3f5aae3d0cbf2b535fe1c5fa4a466ddfbb8ccee9a97e8e1fc8a",
          "sha256": "f9f77bbbdeb686b6b05930e821d621d48aa750a6272c70962a11a4d4afb962bd",
          "sha1": "2a86fcb2ca321cd2276f3335748bb50385638932",
          "md5": "bde6155a74b0daf4d662691b47885f4b"
        }
      ]
    }
  ]
}
