{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.ricoh.cotos",
    "module": "electric-common-libraries",
    "version": "0.0.310",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "electric-common-libraries-0.0.310-plain.jar",
          "url": "electric-common-libraries-0.0.310-plain.jar",
          "size": 828443,
          "sha512": "e37c8a054c94d3e06321bb9f885c752e4c6532f1ac44640d4a2f64d453b8ae107df6d2b15d91ee1ab8618c2cdda0ff1d05c5cba3e0bd8a5a0a9ecdeb6e63e1b6",
          "sha256": "235ca28ae4d4e21a4e3584a81b2349cc86928eb393fca0162ac53a5c8c1bb313",
          "sha1": "3ee3651f39f231f5d59df36cb64c07918aef79da",
          "md5": "8303717f1ce4201cb0ecbefc1a7b5770"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-mail",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.14"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.2.Final"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.2.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jxls",
          "module": "jxls",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jxls",
          "module": "jxls-poi",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "3.17"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "jp.co.ricoh.cotos",
          "module": "dentos-common-libraries",
          "version": {
            "requires": "0.0.368"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger2",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger-ui",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "io.swagger",
          "module": "swagger-core",
          "version": {
            "requires": "1.5.15"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.apache.axis",
          "module": "axis",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "javax.xml",
          "module": "jaxrpc-api",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "wsdl4j",
          "module": "wsdl4j",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "commons-discovery",
          "module": "commons-discovery",
          "version": {
            "requires": "0.5"
          }
        },
        {
          "group": "log4j",
          "module": "log4j",
          "version": {
            "requires": "1.2.17"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.17.5"
          }
        },
        {
          "group": "com.oracle.database.jdbc",
          "module": "ojdbc8",
          "version": {
            "requires": "23.7.0.25.01"
          }
        },
        {
          "group": "javax.xml.soap",
          "module": "javax.xml.soap-api",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-devtools",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "electric-common-libraries-0.0.310-plain.jar",
          "url": "electric-common-libraries-0.0.310-plain.jar",
          "size": 828443,
          "sha512": "e37c8a054c94d3e06321bb9f885c752e4c6532f1ac44640d4a2f64d453b8ae107df6d2b15d91ee1ab8618c2cdda0ff1d05c5cba3e0bd8a5a0a9ecdeb6e63e1b6",
          "sha256": "235ca28ae4d4e21a4e3584a81b2349cc86928eb393fca0162ac53a5c8c1bb313",
          "sha1": "3ee3651f39f231f5d59df36cb64c07918aef79da",
          "md5": "8303717f1ce4201cb0ecbefc1a7b5770"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "electric-common-libraries-0.0.310-sources.jar",
          "url": "electric-common-libraries-0.0.310-sources.jar",
          "size": 282168,
          "sha512": "1c2f3f2f593c2aa28ff2707aae0e8b30079fc065f80ed9e58919ed49bae7130a91335c8a475a5891c82231c5062492e6f5085ba301704918b45d0b486fab6cfc",
          "sha256": "05b1d07388ec0c8fdebdec22d7db1540d09af07e6d679f68276423289820b03b",
          "sha1": "f761f4fa7f6a48676133ce2d91f6ada91f99712f",
          "md5": "291ec106821e46a843e0df838f1d6662"
        }
      ]
    }
  ]
}
